# Taller tuberias en Tensor Flow - Parte 1
### Autor: Samuel Mesa
### Fecha: 1 de mayo de 2021

**Objetivo**: Un cuaderno, escrito de sus manos, repitiendo y si desean modificando el primer cuaderno.

Importar las librerías para la lectura de datos, gráficas y para definir el modelo de los datos

In [7]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt

## Introducción a tensores
A continuación se realiza como se crean tensores

### Declaración de una constante y su visualización

In [8]:
t0 = tf.constant(4)
print(t0)

t1 = tf.constant([1, 3, 4])
print(t1)

t23 = tf.constant([[1, 2, 3],[4, 5, 6]])
print(t23)

tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor([1 3 4], shape=(3,), dtype=int32)
tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


#### Declaración de constantes a partir de una matriz

In [9]:
t235 = tf.constant([[[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]],
                    [[16,17,18,19,20],[21,22,23,24,25],[26,27,28,29,30]]])
print(t235)

tf.Tensor(
[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]]

 [[16 17 18 19 20]
  [21 22 23 24 25]
  [26 27 28 29 30]]], shape=(2, 3, 5), dtype=int32)


#### Se  utiliza numpy 

In [10]:
print(t235.numpy())
print(t235.numpy().shape)

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]]

 [[16 17 18 19 20]
  [21 22 23 24 25]
  [26 27 28 29 30]]]
(2, 3, 5)


#### Algebra mínima de tensores.

In [11]:
a = tf.constant([[1,2],[3,4]])
b = tf.constant([[5,6],[7,8]])

print(a,"\n")
print(b,"\n")
print("Suma de tensores a+b:  \n",tf.add(a,b),"\n")
print("Multiplicación de tensores a*b:  \n",tf.multiply(a,b),"\n")
print(tf.matmul(a,b),"\n")

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[5 6]
 [7 8]], shape=(2, 2), dtype=int32) 

Suma de tensores a+b:  
 tf.Tensor(
[[ 6  8]
 [10 12]], shape=(2, 2), dtype=int32) 

Multiplicación de tensores a*b:  
 tf.Tensor(
[[ 5 12]
 [21 32]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32) 



#### Otras forma de realizar operaciones aritméticas con los tensores 

In [12]:
print("Suma de tensores a+b:  \n",a+b,"\n")
print("Multiplicación de tensores a*b:  \n", a*b, "\n")
print(a@b, "\n")

Suma de tensores a+b:  
 tf.Tensor(
[[ 6  8]
 [10 12]], shape=(2, 2), dtype=int32) 

Multiplicación de tensores a*b:  
 tf.Tensor(
[[ 5 12]
 [21 32]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32) 



#### Funcion de reducción

In [13]:
c = tf.constant([[4.0, 5.0],[10.0,1.0]])

print(c,"\n")
print("Máximo elemento: ",tf.reduce_max(c),"\n")
print("Mínimo elemento: ",tf.reduce_min(c),"\n")
print("Media del tensor:  ",tf.reduce_mean(c),"\n")
print("Retorna la posición en el tensor del elemento mas grande: ",tf.argmax(c),"\n")
print("Uso de función de reducción: ",tf.nn.softmax(c),"\n")
print(tf.reduce_sum(tf.nn.softmax(c),axis=1),"\n")

tf.Tensor(
[[ 4.  5.]
 [10.  1.]], shape=(2, 2), dtype=float32) 

Máximo elemento:  tf.Tensor(10.0, shape=(), dtype=float32) 

Mínimo elemento:  tf.Tensor(1.0, shape=(), dtype=float32) 

Media del tensor:   tf.Tensor(5.0, shape=(), dtype=float32) 

Retorna la posición en el tensor del elemento mas grande:  tf.Tensor([1 0], shape=(2,), dtype=int64) 

Uso de función de reducción:  tf.Tensor(
[[2.6894143e-01 7.3105860e-01]
 [9.9987662e-01 1.2339458e-04]], shape=(2, 2), dtype=float32) 

tf.Tensor([1. 1.], shape=(2,), dtype=float32) 



### Tipo, forma y dimensión

In [14]:
t = tf.constant([
  [[0, 1, 2, 3, 4],
   [5, 6, 7, 8, 9]],
  [[10, 11, 12, 13, 14],
   [15, 16, 17, 18, 19]],
  [[20, 21, 22, 23, 24],
   [25, 26, 27, 28, 29]],])
print("Tipo de tensor: \n",t.dtype,"\n")
print("Descripciones del tensor: \n",t.shape,"\n")
print("Dimensiones del tensor: \n",t.ndim,"\n")
print("Descripción t.shape[2]: \n",t.shape[2],"\n")
print("Tamano del tensor: \n",tf.size(t.numpy()),"\n")

Tipo de tensor: 
 <dtype: 'int32'> 

Descripciones del tensor: 
 (3, 2, 5) 

Dimensiones del tensor: 
 3 

Descripción t.shape[2]: 
 5 

Tamano del tensor: 
 tf.Tensor(30, shape=(), dtype=int32) 



### Indexación
Indexación en un solo eje
Los índices empiezan en cero.
Los índices negativos cuentan hacia atrás desde el final.
Los dos puntos (:) se utilizan para los cortes. inicio:final:salto

In [16]:
t1 =  tf.constant([0, 1, 1, 2, 3, 5, 8, 13, 21, 34])
print("Primero: ", t1[0])
print("Segundo: ", t1[1])
print("Ultimo: ", t1[-1].numpy())

Primero:  tf.Tensor(0, shape=(), dtype=int32)
Segundo:  tf.Tensor(1, shape=(), dtype=int32)
Ultimo:  34


## Extracción de parte de un tensor: slices¶

In [17]:
print('Todo', t1[:].numpy())
print('Antes la posición 4 ', t1[:4].numpy())
print('Desde la posición 4 hasta el final', t1[4:].numpy())
print('Desde la posición 2 hasta anterior a 7', t1[4:7].numpy())
print('Todos los elementos en posición par ', t1[::2].numpy())
print('Invertido todo el orden', t1[::-1].numpy())

Todo [ 0  1  1  2  3  5  8 13 21 34]
Antes la posición 4  [0 1 1 2]
Desde la posición 4 hasta el final [ 3  5  8 13 21 34]
Desde la posición 2 hasta anterior a 7 [3 5 8]
Todos los elementos en posición par  [ 0  1  3  8 21]
Invertido todo el orden [34 21 13  8  5  3  2  1  1  0]


### Indexación multi-eje

In [19]:
t23 = tf.constant([[1, 2, 3],[4, 5, 6]])
print(t23.numpy())

# Algunas indexaciones 
print('Posición 1,1 = ',t23[1,1].numpy())
print('Segunda fila: ', t23[1,:].numpy())
print('Segunda columna: ', t23[:,1].numpy())
print('Última columna: ', t23[:,-1].numpy())
print('Primer elemento de la última columna: ', t23[0,-1].numpy())
print('Saltarse la primera columna: \n', t23[:,1:].numpy()) 

[[1 2 3]
 [4 5 6]]
Posición 1,1 =  5
Segunda fila:  [4 5 6]
Segunda columna:  [2 5]
Última columna:  [3 6]
Primer elemento de la última columna:  3
Saltarse la primera columna: 
 [[2 3]
 [5 6]]


### Ejemplo de cubo de un tensor

In [20]:
t = tf.constant([
  [[0, 1, 2, 3, 4],
   [5, 6, 7, 8, 9]],
  [[10, 11, 12, 13, 14],
   [15, 16, 17, 18, 19]],
  [[20, 21, 22, 23, 24],
   [25, 26, 27, 28, 29]],]) 
print(t.numpy())

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]]


### Extracciones de info del tensor

In [21]:
print('Extrae la primera capa\n', t[0,:,:])
print('Extrae la segunda capa\n', t[1])

Extrae la primera capa
 tf.Tensor(
[[0 1 2 3 4]
 [5 6 7 8 9]], shape=(2, 5), dtype=int32)
Extrae la segunda capa
 tf.Tensor(
[[10 11 12 13 14]
 [15 16 17 18 19]], shape=(2, 5), dtype=int32)


### Manipular formas y remodelando el tensor

In [22]:
x = tf.constant([[1],[2],[3],[4]])
print(x.shape)
print(x.shape.as_list())
print("Remodelando el tensor \n")
reshaped = tf.reshape(x,[2,2])
print(reshaped.numpy())
print(x.numpy())

(4, 1)
[4, 1]
Remodelando el tensor 

[[1 2]
 [3 4]]
[[1]
 [2]
 [3]
 [4]]


### Aplanar un tensor

In [23]:
print("t actual: \n", t.numpy())
flat = tf.reshape(t, [-1])
print("\n t aplanado: \n", flat.numpy())

t actual: 
 [[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]]

 t aplanado: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]


### Mirar un tensor como una lista

In [24]:
print(t.shape.as_list())
print("tf.reshape(t, [2*3,5]).....:\n")
print(tf.reshape(t, [2*3,5]))
print("tf.reshape(t, [2,3*5]).....:\n")
print(tf.reshape(t, [2,3*5]))

[3, 2, 5]
tf.reshape(t, [2*3,5]).....:

tf.Tensor(
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]], shape=(6, 5), dtype=int32)
tf.reshape(t, [2,3*5]).....:

tf.Tensor(
[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]], shape=(2, 15), dtype=int32)


### Otras impresiones con reshape

In [25]:
print("Tensor original:: ",t.shape.as_list())
print(tf.reshape(t, [-1,5]))
print(tf.reshape(t, [3,-1]))
print(tf.reshape(t, [3,2,5])) #Es el mismo original

Tensor original::  [3, 2, 5]
tf.Tensor(
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]], shape=(6, 5), dtype=int32)
tf.Tensor(
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]], shape=(3, 10), dtype=int32)
tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]], shape=(3, 2, 5), dtype=int32)


### Definición Conversión de tipos. Cast

In [26]:
f64_tensor = tf.constant([2.0, 4.0, 6.0], dtype = tf.float64)
print(f64_tensor)

f16_tensor = tf.cast(f64_tensor,dtype= tf.float16)
print(f16_tensor)

u8_tensor = tf.cast(f16_tensor, dtype = tf.uint8)
print(u8_tensor)

tf.Tensor([2. 4. 6.], shape=(3,), dtype=float64)
tf.Tensor([2. 4. 6.], shape=(3,), dtype=float16)
tf.Tensor([2 4 6], shape=(3,), dtype=uint8)


### Radiofusión (broadcasting)
La radiodifusión es un concepto tomado de la función equivalente en NumPy . En resumen, bajo ciertas condiciones, los tensores más pequeños se "estiran" 
automáticamente para adaptarse a tensores más grandes cuando se ejecutan operaciones combinadas en ellos.

El caso más simple y común es cuando intenta multiplicar o agregar un tensor a un escalar. En ese caso, el escalar se transmite para que tenga la misma forma que el otro argumento.

In [27]:
x = tf.constant([1, 2 ,3])
y = tf.constant(2)
z = tf.constant([2, 2 ,2])

# el mismo resultado
print(tf.multiply(x,2))
print(x*y)
print(x*z)

tf.Tensor([2 4 6], shape=(3,), dtype=int32)
tf.Tensor([2 4 6], shape=(3,), dtype=int32)
tf.Tensor([2 4 6], shape=(3,), dtype=int32)


### Remodelado

In [28]:
x = tf.reshape(x, [3,1])
y = tf.range(1,5)
print("Tensor X: ",x, "\n")
print("Tensor Y: ",y, "\n")

Tensor X:  tf.Tensor(
[[1]
 [2]
 [3]], shape=(3, 1), dtype=int32) 

Tensor Y:  tf.Tensor([1 2 3 4], shape=(4,), dtype=int32) 



### Multiplicación
Del mismo modo, los ejes con longitud 1 se pueden estirar para que coincidan con los otros argumentos. 
Ambos argumentos se pueden estirar en el mismo cálculo.

En este caso, una matriz de 3x1 se multiplica por elementos por una matriz de 1x4 para producir 
una matriz de 3x4. Observe que el 1 inicial es opcional: la forma de y es [4]. En matemáticas 
esta multiplicación se conoce como producto externo.

In [29]:
print(tf.multiply(x,y))

tf.Tensor(
[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]], shape=(3, 4), dtype=int32)


### tf.broadcast_to

In [30]:
print(tf.broadcast_to([1,2,3], [3,3]))

tf.Tensor(
[[1 2 3]
 [1 2 3]
 [1 2 3]], shape=(3, 3), dtype=int32)


### tf.convert_to_tensor
La mayoría de las operaciones, como tf.matmul y tf.reshape toman argumentos de la clase tf.Tensor. 
Sin embargo, notará que en el caso anterior, se aceptan objetos de Python con forma de tensores.

La mayoría, pero no todas, las operaciones llaman a tf.convert_to_tensor con argumentos no tensoriales. 
Existe un registro de conversiones, y la mayoría de las clases de objetos como ndarray , TensorShape ,
de Python, y tf.Variable se convertirán todas automáticamente.

### Tensores irregulares (ragged tensors) 
Un tensor con números variables de elementos a lo largo de algún eje se llama "irregular".
 Utilice tf.ragged.RaggedTensor para datos irregulares.

Por ejemplo, esto no se puede representar como un tensor regular:

In [32]:
ragged_list = [
    [0, 1, 2, 3],
    [4, 5],
    [6, 7, 8],
    [9]]

try:
    tensor = tf.constant(ragged_list)
except Exception as e:
     print(f"{type(e).__name__}: {e}")
     
# En su lugar, cree un tf.RaggedTensor usando tf.ragged.constant :
ragged_t = tf.ragged.constant(ragged_list)
print(ragged_t.shape)

ValueError: Can't convert non-rectangular Python sequence to Tensor.
(4, None)


Tensores de strings

In [36]:
st = tf.constant("Este tensor string")
print(st)

st = tf.constant(["Este tensor string",
                 "Cadena 2",
                 "Cadena 3",
                 "Cadena 4"])
print(st)
print(tf.strings.split(st))

tf.Tensor(b'Este tensor string', shape=(), dtype=string)
tf.Tensor([b'Este tensor string' b'Cadena 2' b'Cadena 3' b'Cadena 4'], shape=(4,), dtype=string)
<tf.RaggedTensor [[b'Este', b'tensor', b'string'], [b'Cadena', b'2'], [b'Cadena', b'3'], [b'Cadena', b'4']]>


### string to number

In [37]:
st = tf.constant("1 10 10.4")
print(tf.strings.to_number(tf.strings.split(st, " ")))

tf.Tensor([ 1.  10.  10.4], shape=(3,), dtype=float32)


### Tensores dispersos. SparseTensor
Se crea en tensor de 3 filas por 4 columnas [3,4], en la celda [0,1] esta el elemento 1
en la celda [1,2] esta el elemento 2 
en el ejemplo segundo:
Se crea en tensor de 3 filas por 10 columnas [3,10], en la celda [0,3] esta el elemento 10
en la celda [2,4] esta el elemento 20.     

In [38]:
#  tensor disperso Ejemplo 1
sparse_tensor = tf.sparse.SparseTensor(indices = [[0,1], [1,2]],
                                       values = [1,2],
                                       dense_shape
                                        =[3,4])
print(sparse_tensor, " Ejemplo 1\n")

# convierte a tensor denso
print(tf.sparse.to_dense(sparse_tensor))


#  tensor disperso Ejemplo 2
st1 = tf.SparseTensor(indices=[[0, 3], [2, 4]],
                      values=[10, 20],
                      dense_shape=[3, 10])

print(st1, " Ejemplo 2\n")

# convierte a tensor denso
print(tf.sparse.to_dense(st1))

SparseTensor(indices=tf.Tensor(
[[0 1]
 [1 2]], shape=(2, 2), dtype=int64), values=tf.Tensor([1 2], shape=(2,), dtype=int32), dense_shape=tf.Tensor([3 4], shape=(2,), dtype=int64))  Ejemplo 1

tf.Tensor(
[[0 1 0 0]
 [0 0 2 0]
 [0 0 0 0]], shape=(3, 4), dtype=int32)
SparseTensor(indices=tf.Tensor(
[[0 3]
 [2 4]], shape=(2, 2), dtype=int64), values=tf.Tensor([10 20], shape=(2,), dtype=int32), dense_shape=tf.Tensor([ 3 10], shape=(2,), dtype=int64))  Ejemplo 2

tf.Tensor(
[[ 0  0  0 10  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0 20  0  0  0  0  0]], shape=(3, 10), dtype=int32)


## Conclusiones

Se realiza la revisión de las operaciones y a relación entre tensores y matrices de NumPy